const data = {
  products: [
    {
      _id: '1',
       price : 750,
       countInStock : 9,
       rating : 0,
       numReviews : 0,
       name :  "Maharaja Dosa" ,
       image : " /images/indian3.jpg ",
       brand :  "Dennis Lingo" ,
       category :  "indian" ,
       description : " high quality food ",
       __v : 0
    },
    {
      _id: '2',
       price : 322,
     countInStock : 9,
     rating : 0,
     numReviews : 0,
     name :  "Royal cake Pastery" ,
     image :  "/images/dessert1.webp" ,
     brand :  "Cake world" ,
     category :  "dessert" ,
     description :  "high quality food" ,
     __v : 0
    },
    {
      _id: '3',
       price : 383,
     countInStock : 9,
     rating : 0,
     numReviews : 0,
     name : "Banana cream shake" ,
     image :  "/images/dessert3.jpg" ,
     brand :  "Blue restaurent" ,
     category :  "dessert" ,
     description :  "high quality" ,
     __v : 0
    },
    {
      _id: '4',
     
       price : 1799,
       countInStock : 9,
       rating : 0,
       numReviews : 0,
       name :  "Gujrati mithai" ,
       image :  '/images/dessert2.jpg" ,
       brand :  "blue ocean" ,
       category :  "dessert" ,
       description :  "high quality" ,
       __v : 0
    },
    {
      _id: '5',
       price : 1050,
       countInStock : 9,
       rating : 0,
       numReviews : 0,
       name :  "Rajasthani thali, Paneer Parantha" ,
       image :  "/images/indian2.webp" ,
       brand :  "Magic World" ,
       category :  "indian" ,
       description :  "high quality food" ,
       __v : 0
    },
    {
      _id: '6',
       price : 3132,
     countInStock : 9,
     rating : 0,
     numReviews : 0,
     name :  "Royal Veg Biriyani, Aloo Gobi, Paneer, Nan Parantha" ,
     image :  "/images/indian1.webp" ,
     brand :  "Royal Restaurent" ,
     category :  "indian" ,
     description :  "High quality food"  ,
     __v : 0
    },
    {
      _id: '7',
       price : 3047,
     countInStock : 9,
     rating : 0,
     numReviews : 0,
     name :   "McDonald’s “McOz” Burger" ,
     image :  "/images/burger3.webp" ,
     brand :  "McDonald’s" ,
     category :  "burger" ,
     description :  "American and Australian style burgers, having beetroot and tomato in an otherwise typical American burger." ,
     __v : 0
    },
    {
      _id: '8',
       price : 899,
       countInStock : 9,
       rating : 0,
       numReviews : 0,
       name :  "Double Decker' ,
       image :  "/images/burger2.webp" ,
       brand :  "Tryme" ,
       category :  "burger" ,
       description :  "A hamburger with two patties is a “double decker” or simply a “double,” " ,
       __v : 0
    },
    {
      _id: '9',
       price : 329,
       countInStock : 9,
       rating : 0,
       numReviews : 0,
       name :  "Cheeseburger ",
       image :  "/images/burger1.webp" ,
       brand :  "Esomic" ,
       category :  "burger" ,
       description :  "The cheese is usually sliced, then added a short time before the hamburger finishes cooking to allow it to melt. In fast food restaurants, the cheese that is added to a cheeseburger is typically American cheese, but there are many other variations. Mozzarella, blue cheese, pepper jack, and especially cheddar are popular choices." ,
       __v : 0
    },
    {
      _id: '10',
       price : 690,
       countInStock : 9,
       rating : 0,
       numReviews : 0,
       name :  "Greek Pizza" ,
       image :  "/images/pizza3.webp" ,
       brand :  "mexican" ,
       category :  "pizza" ,
       description :  "Greek pizza is usually heavier on the sauce than the cheese. The sauce typically has a tangy tomato paste with a strong oregano flavor. It is often only topped with cheese, which is usually a mix of mozzarella and cheddar or provolone. It may feature a variety of non-Greek or Greek toppings, such as feta cheese, black olives, and red onion." ,
       __v : 0
    },
    {
      _id: '11',
       price : 379,
       countInStock : 9,
       rating : 0,
       numReviews : 0,
       name :  "Sicilian Pizza" ,
       image :  "/images/pizza2.webp" ,
       brand :  "italian" ,
       category :  "pizza" ,
       description :  "Sicilian pizzas are often topped with bits of tomato, onion, anchovies, and herbs." ,
       __v : 0
    },
    {
      _id: '12',
       price : 689,
     countInStock : 9,
     rating : 0,
     numReviews : 0,
     name :  "Neapolitan Pizza" ,
     image :  "/images/pizza4.webp" ,
     brand :  "Pizza Margherita" ,
     category :  "pizza" ,
     description :  "Features tomatoes, sliced mozzarella, basil, and extra virgin olive oil. ",
     __v : 0
    },
  ],
};
export default data;