const data = {
    products: [
      {
        _id: '1',
        name: 'Burger',
        category: 'Shirts',
        image: '/images/p1.webp',
        price: 120,
        brand: 'burger',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '2',
        name: 'Cakes',
        category: 'Shirts',
        image: '/images/p2.webp',
        price: 100,
        brand: 'pasteries',
        rating: 4.0,
        numReviews: 10,
        description: 'high quality product',
      },
      
      {
        _id: '4',
        name: 'Mexican Pizza',
        category: 'Pants',
        image: '/images/p4.webp',
        price: 78,
        brand: 'pizza',
        rating: 4.5,
        numReviews: 14,
        description: 'high quality product',
      },
      {
        _id: '5',
        name: 'Geek Pizza',
        category: 'Pants',
        image: '/images/p5.webp',
        price: 65,
        brand: 'Pizza',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '6',
        name: 'Rajasthani thali',
        category: 'Pants',
        image: '/images/p6.webp',
        price: 139,
        brand: 'Adidas',
        rating: 4.5,
        numReviews: 15,
        description: 'high quality product',
      },
    ],
  };
  export default data;